apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: aws-us-east-1
spec:
  configuration: |
    terraform {
      backend "s3" {
        bucket = "xplanetfstate"
        key    = "terraform.tfstate"
        region = "us-east-1"
        access_key = "KEY"
        secret_key = "SECRET"
      }
    }
    provider "aws" {
      shared_credentials_file = "aws-creds.ini"
      region = "us-east-1"
    }
  credentials:
    - filename: aws-creds.ini
      secretRef:
        key: creds
        name: aws-creds
        namespace: crossplane-system
      source: Secret